# Generated by Django 5.1.7 on 2026-05-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetalert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("threshold_reached", "Limite atingido"),
                    ("warning", "Atenção"),
                    ("exceeded", "Ultrapassado"),
                ],
                max_length=30,
            ),
        ),
    ]
